### ISSUE TITLE
Math coming out 𝙫𝙚𝙧𝙮 bold.

### ISSUE THREAD

**Issue by tim-fi** [doersino/markdeep-thesis#4]
Hi, I'm currently writing my Bachelor-Thesis using this project and find it a very comfortable experience so far.
But sadly when I go to "print my thesis to pdf" all the the math comes out really, and I mean **really** bold:
![image](https://user-images.githubusercontent.com/30415153/90036051-d693d480-dcc2-11ea-8a5e-9c579c106a2a.png)

I'm printing via `Chromium Version 84.0.4147.89 (Official Build) Arch Linux (64-bit)`, in case that is of any importance here...

**Comment by tim-fi** [comment]
Just tried it on `Mozilla Firefox 79.0 (64-bit) for Manjaro Linux` and it does the same...

**Comment by doersino** [comment]
That's because MathJax is configured to render math as SVG paths, while the surrounding text is text (duh). Your PDF reader appears to use different anti-aliasing algorithms for vector graphics and text, making the former appear bolder.

This effect should gradually diminish as you zoom into the document – and it doesn't affect print quality at all.

*(Im Übrigen: Meine intensiven Nachforschungen ergeben, dass du deine Arbeit bei Torsten Grust schreibst – bei meiner Masterarbeit, für die ich dieses Tool gebaut habe, hat er sich nicht über zu fettes Math-Rendering beschwert. 😉)*

**Comment by tim-fi** [comment]
Yeah, just confirmed it `Evince` (Gnome's Document Viewer) seems to be the issue here. `mupdf` doesn't have this rendering artifact...

_(Gut zu wissen! :grin: )_
